export const projects = [
  {
    title: "Task Manager",
    subtitle: "MERN Stack",
    description:"A web-based platform that incorporates a dynamic work allocation algorithm to facilitate efficient task assignment within our software development team. The primary objective is to enhance team productivity by ensuring a balanced and fair distribution of tasks, considering individual team members' skills, availability, and existing workload.",
    image: "./project1.png",
    link: "https://taskify-vrdev.netlify.app/",
  },
  {
    title: "Clubify",
    subtitle: "MERN Stack",
    description:"Clubify is a cutting-edge web application designed to revolutionize the way college clubs manage and promote their events. With Clubify, gone are the days of cumbersome spreadsheets and disorganized event planning. Our platform empowers college clubs to effortlessly update, list, maintain, and control all aspects of their events.",
    image: "./project2.png",
    link: "https://github.com/rishi9808/Clubify",
  },
  {
    title: "IMAGE-AI",
    subtitle: "React, DALL-E API",
    description:"A community page to create and share creative images generated by DALL-E",
    image: "./project3.png",
    link: "https://dashing-dodol-5dead0.netlify.app/",
  },
  
];



export const skills = [
  "JavaScript",
  "React",
  "Python",
  "Node",
  "TailwindCSS",
  "MongoDB",
];
